name: CI

# Controls when the workflow will run
on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pass the PR branch to internal GL to run pipelines
        run: |
          git remote add internal https://gitlab-ci-token:${{ secrets.GL_TOKEN }}@gitlab.hanaboso.net/husak.j/github-poc.git
          # toho: resolve name clashes
          git push internal ${GITHUB_HEAD_REF}
